[tool.poetry]
name = "web-model-2"
version = "0.1.0"
description = ""
authors = ["a.chernov <chernovartem522@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
